config/routes.rb
Liberatio::Application.routes.draw do

  resources :subscriptions do
    get 'welcome', :on => :collection, :as => "welcome"
  end

  get "au/latest" => "automatic_updates#latest"

  resources :issues

  resources :responses
  resources :tickets

  post "pusher/auth" => "pusher#auth"
  post "pusher/webhook" => "pusher#webhook"

  get "browse/home" => "browse#home"
  get "browse/about" => "browse#about", :as => "browse_about"
  get "browse/contacts" => "browse#contacts", :as => "browse_contacts"
  get "browse/privacy" => "browse#privacy", :as => "browse_privacy"
  get "browse/pricing" => "browse#pricing", :as => "browse_pricing"
  get "browse/features" => "browse#features", :as => "browse_features"
  get "browse/buy" => "browse#buy", :as => "browse_buy"
  get "browse/download" => "browse#download", :as => "browse_download"
  get "browse/getting_started" => "browse#getting_started", :as => "browse_getting_started"
  get "browse/faq" => "browse#faq", :as => "browse_faq"
  get "browse/documentation" => "browse#documentation", :as => "browse_documentation"
  get "browse/configuring_agent" => "browse#configuring_agent", :as => "browse_configuring_agent"

  resources :inventories, :only => :create
  resources :users do
    get 'settings', :on => :member, :as => 'settings'
  end
  resources :instances
  resources :applications
  resources :organizations do
    resources :hosted_files
    resources :notes
    get 'regenerate_registration_code', on: :collection
  end
  resources :nodes do
    resources :commands
    resources :hosted_files
    resources :notes
    get 'registered', :on => :collection
    post 'register', :on => :collection
    get 'maintenance', :on => :collection, :as => "maintenance"
    get 'dashboard', :on => :collection, :as => "dashboard"
  end

  resources :sessions
  get "sessions/new" => "sessions#new", :as => "login"
  delete "sessions/destroy" => "sessions#destroy", :as => "logout"
  get "sessions/forgot_password" => "sessions#forgot_password", :as => "forgot_password"

  root 'browse#home'
end

app/models/node.rb
# -----------------------------------------------------------------------------
# This file is a part of Liberatio, a systems management Web application.
# The text in this file is subject to the terms defined in the LICENSE file.
#
# Copyright 2014, Joshua Shane Martin
# All Rights Reserved
# -----------------------------------------------------------------------------

class Node < ActiveRecord::Base
  # callbacks
  before_validation :generate_uuid, :on => :create
  before_create :regenerate_token!

  # relationships
  belongs_to :organization
  has_many :commands, dependent: :destroy
  has_many :hosted_files, dependent: :destroy
  has_many :instances, dependent: :destroy
  has_many :memories, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :processors, dependent: :destroy
  has_many :disks, dependent: :destroy
  has_many :updates, dependent: :destroy
  
  # validations
  validates :uuid, :organization, presence: true
  validates :role, :inclusion => { :in => ["Domain Controller", "Phone", "Router", "Server", "Tablet", "Workstation"] }, :if => Proc.new { |node| node.role.present? }
  validates :name, presence: true, :if => Proc.new { |node| !node.is_managed? }
  # validates :operating_system, :inclusion => {:in => Node.operating_systems}

  # validate :validate_operating_system_in_operating_systems
  # def validate_operating_system_in_operating_systems
  #   errors.add(:base, "Operating system is not valid") if not Node.operating_systems.include?(self.operating_system)
  # end

  # Returns a newly created or updated node object for the given uuid. The
  # node will belong to the organization with the given registration code and
  # will have its communications token regenerated before being returned.
  def self.update_or_create_from_uuid(hsh = {})
    @organization = Organization.where(registration_code: hsh[:registration_code]).first
    @node = @organization.nodes.find_or_create_by(uuid: hsh[:uuid])
    @node.is_managed = true
    @node.regenerate_token!
    return @node
  end

  # Updates the node with the given id to the given status
  def self.update_status(hsh = {})
    @node = Node.find(hsh[:id])
    unless @node.blank?
      @node.update(status: hsh[:status])
    end
  end
  
  def inventory(inventory)
    self.update(inventory.except(:uuid, :applications, :memory, :processor, :disks, :updates).merge(:inventoried_at => Time.now))

    # applications
    self.instances.destroy_all
    if inventory[:applications].present?
      inventory[:applications].each do |a|
        application = Application.find_or_create_by( name: a[:name],
                                                     publisher: a[:publisher],
                                                     version: a[:version] )

        self.instances << self.instances.new(application_id: application.id, organization_id: self.organization_id)
      end
    end

    # memories
    self.memories.destroy_all
    if inventory[:memory].present?
      inventory[:memory].each do |m|
        self.memories << self.memories.new( capacity: m[:capacity],
                                            form_factor: m[:form_factor],
                                            manufacturer: m[:manufacturer],
                                            memory_type: m[:memory_type],
                                            speed: m[:speed])
      end
    end

    # processors
    self.processors.destroy_all
    if inventory[:processor].present?
      inventory[:processor].each do |p|
        self.processors << self.processors.new( architecture: p[:architecture],
                                                name: p[:name],
                                                cores_count: p[:cores_count],
                                                speed: p[:speed])
      end
    end

    # disks
    self.disks.destroy_all
    if inventory[:disks].present?
      inventory[:disks].each do |d|
        self.disks << self.disks.new( disk_type: d[:disk_type],
                                      file_system: d[:file_system],
                                      free_bytes: d[:free_bytes],
                                      total_bytes: d[:total_bytes],
                                      volume_name: d[:volume_name])
      end
    end

    # updates
    self.updates.destroy_all
    if inventory[:updates].present?
      inventory[:updates].each do |u|
        self.updates << self.updates.new( title: u[:title],
                                          severity: u[:severity],
                                          support_url: u[:support_url],
                                          is_installed: u[:is_installed],
                                          organization_id: self.organization_id )
      end
    end

    return self.save
  end


  def can_edit_special_field?
    if self.id.blank?
      return true
    else
      if self.is_managed?
        return false
      else
        return true
      end
    end
  end

  def online?
    response = Pusher.get("/channels/presence-cmd_#{self.uuid}/users")
    response[:users].any? { |u| u["id"] == self.id.to_s }
  end


  def self.operating_systems
    oses = []
    oses << "Red Hat Enterprise Linux 3"
    oses << "Red Hat Enterprise Linux 3.1"
    oses << "Red Hat Enterprise Linux 3.2"
    oses << "Red Hat Enterprise Linux 3.3"
    oses << "Red Hat Enterprise Linux 3.4"
    oses << "Red Hat Enterprise Linux 3.5"
    oses << "Red Hat Enterprise Linux 3.6"
    oses << "Red Hat Enterprise Linux 3.7"
    oses << "Red Hat Enterprise Linux 3.8"
    oses << "Red Hat Enterprise Linux 3.9"
    oses << "-"
    oses << "Red Hat Enterprise Linux 4"
    oses << "Red Hat Enterprise Linux 4.1"
    oses << "Red Hat Enterprise Linux 4.2"
    oses << "Red Hat Enterprise Linux 4.3"
    oses << "Red Hat Enterprise Linux 4.4"
    oses << "Red Hat Enterprise Linux 4.5"
    oses << "Red Hat Enterprise Linux 4.6"
    oses << "Red Hat Enterprise Linux 4.7"
    oses << "Red Hat Enterprise Linux 4.8"
    oses << "Red Hat Enterprise Linux 4.9"
    oses << "-"
    oses << "Red Hat Enterprise Linux 5"
    oses << "Red Hat Enterprise Linux 5.1"
    oses << "Red Hat Enterprise Linux 5.2"
    oses << "Red Hat Enterprise Linux 5.3"
    oses << "Red Hat Enterprise Linux 5.4"
    oses << "Red Hat Enterprise Linux 5.5"
    oses << "Red Hat Enterprise Linux 5.6"
    oses << "Red Hat Enterprise Linux 5.7"
    oses << "Red Hat Enterprise Linux 5.8"
    oses << "Red Hat Enterprise Linux 5.9"
    oses << "Red Hat Enterprise Linux 5.10"
    oses << "-"
    oses << "Red Hat Enterprise Linux 6"
    oses << "Red Hat Enterprise Linux 6.1"
    oses << "Red Hat Enterprise Linux 6.2"
    oses << "Red Hat Enterprise Linux 6.3"
    oses << "Red Hat Enterprise Linux 6.4"
    oses << "Red Hat Enterprise Linux 6.5"
    oses << "-"
    oses << "Red Hat Enterprise Linux 7"
    oses << "-"
    oses << "Windows 95"
    oses << "Windows 98"
    oses << "Windows 98 SE"
    oses << "Windows ME"
    oses << "-"
    oses << "Windows NT 4.0 Workstation"
    oses << "Windows NT 4.0 Embedded"
    oses << "-"
    oses << "Windows 2000 Professional"
    oses << "-"
    oses << "Windows XP Starter"
    oses << "Windows XP Home"
    oses << "Windows XP Media Center"
    oses << "Windows XP Tablet PC"
    oses << "Windows XP Professional"
    oses << "Windows XP Professional x64"
    oses << "Windows XP 64 bit (Itanium)"
    oses << "-"
    oses << "Windows Vista Starter"
    oses << "Windows Vista Home Basic"
    oses << "Windows Vista Home Basic N"
    oses << "Windows Vista Home Premium"
    oses << "Windows Vista Business"
    oses << "Windows Vista Business N"
    oses << "Windows Vista Enterprise"
    oses << "Windows Vista Ultimate"
    oses << "-"
    oses << "Windows 7 Starter"
    oses << "Windows 7 Home Basic"
    oses << "Windows 7 Home Premium"
    oses << "Windows 7 Professional"
    oses << "Windows 7 Ultimate"
    oses << "Windows 7 Enterprise"
    oses << "-"
    oses << "Windows NT 4.0 Server"
    oses << "Windows NT 4.0 Server, Enterprise"
    oses << "Windows NT 4.0 Server, Terminal Server"
    oses << "-"
    oses << "Windows 2000 Server"
    oses << "Windows 2000 Advanced Server"
    oses << "Windows 2000 Datacenter Server"
    oses << "-"
    oses << "Windows Server 2003 Standard"
    oses << "Windows Server 2003 Web"
    oses << "Windows Server 2003 Enterprise"
    oses << "Windows Server 2003 Datacenter"
    oses << "-"
    oses << "Windows Compute Cluster Server 2003"
    oses << "-"
    oses << "Windows Storage Server 2003"
    oses << "Windows Storage Server 2003 R2"
    oses << "Windows Storage Server 2008"
    oses << "Windows Storage Server 2008 R2"
    oses << "Windows Storage Server 2012"
    oses << "Windows Storage Server 2012 R2"
    oses << "-"
    oses << "Windows Home Server"
    oses << "Windows Home Server 2011"
    oses << "-"
    oses << "Windows Server 2008 Foundation"
    oses << "Windows Server 2008 Standard"
    oses << "Windows Server 2008 Web"
    oses << "Windows Server 2008 HPC"
    oses << "Windows Server 2008 Enterprise"
    oses << "Windows Server 2008 Datacenter"
    oses << "Windows Server 2008 Itanium"
    oses << "-"
    oses << "Windows Small Business Server 2008"
    oses << "Windows Essential Business Server 2008"
    oses << "-"
    oses << "Windows Server 2008 R2 Foundation"
    oses << "Windows Server 2008 R2 Standard"
    oses << "Windows Server 2008 R2 Web"
    oses << "Windows Server 2008 R2 HPC"
    oses << "Windows Server 2008 R2 Enterprise"
    oses << "Windows Server 2008 R2 Datacenter"
    oses << "Windows Server 2008 R2 Itanium"
    oses << "-"
    oses << "Windows Server 2012 Foundation"
    oses << "Windows Server 2012 Essentials"
    oses << "Windows Server 2012 Standard"
    oses << "Windows Server 2012 Datacenter"
    oses << "-"
    oses << "Windows Server 2012 R2 Essentials"
    oses << "Windows Server 2012 R2 Standard"
    oses << "Windows Server 2012 R2 Datacenter"

app/controllers/nodes_controller.rb
# -----------------------------------------------------------------------------
# This file is a part of Liberatio, a systems management Web application.
# The text in this file is subject to the terms defined in the LICENSE file.
#
# Copyright 2014, Joshua Shane Martin
# All Rights Reserved
# -----------------------------------------------------------------------------

class NodesController < ApplicationController
  protect_from_forgery except: :register
  skip_before_filter :authenticate_user!, only: [:register, :registered]
  before_action :require_subscription!
  before_action :set_highlight, except: :maintenance
  before_action :set_navigation
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  respond_to :json

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = current_user.organization.nodes
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  def registered
    @node = Node.where(uuid: params[:uuid]).first
    
    if @node
      render :nothing => true, :status => :ok
    else
      render :nothing => true, :status => :no_content
    end
  end

  # GET /nodes/dashboard
  def dashboard
    @highlight = "dashboard"
  end

  # GET /nodes/maintenance
  def maintenance
    @highlight = "maintenance"

    @devices_needing_updates = current_user.organization.nodes.joins(:updates).where("updates.is_installed = ?", false)
    @devices_with_issues = current_user.organization.issues
    #@updates = current_user.organization.updates.joins(:node).where(:is_installed => false).uniq.pluck("nodes.id").count
    #@issues = current_user.organization.updates.where(:is_installed => false).uniq.pluck("title").count
  end

  # POST /nodes/register
  def register
    @organization = Organization.where(registration_code: params[:registration_code]).first!
    
    raise "Must provide a uuid" if !params.has_key?(:uuid)

    # since the registration code matches, we create
    # or update the node with a token to be returned
    @node = Node.update_or_create_from_uuid(uuid: params[:uuid],
                                            registration_code: @organization.registration_code)

    render :json => @node.to_json( :only => [:uuid, :token] ), :status => :ok
  rescue ActiveRecord::RecordNotFound
    render :json => { :errors => [ "Registration Code is invalid" ] }, :status => :unprocessable_entity
  rescue => error
    render :json => { :errors => error }, :status => :unprocessable_entity
  end

  # GET /nodes/new
  def new
    @node = current_user.organization.nodes.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = current_user.organization.nodes.new(node_params)
    @node.is_managed = false

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Device was successfully added.' }
        format.json { render action: 'show', status: :created, location: @node }
      else
        format.html { render action: 'new' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end

  private
    def set_node
      @node = current_user.organization.nodes.find(params[:id])
    end

    def set_highlight
      @highlight = "devices"
    end

    def set_navigation
      @navigation = "account"
    end

    def node_params
      params.require(:node).permit(:role, :location, :name, :operating_system, :serial_number, :model_number, :is_managed)
    end
end

app/views/nodes/_form.html.haml
.row
  .col-md-7

    = form_for @node, :html => { :class => "form-horizontal", :role => "form" } do |f|

      - if @node.errors.any?
        .alert.alert-danger
          %ul.list-unstyled
            - @node.errors.full_messages.each do |msg|
              %li
                = msg

      .form-group
        = f.label :is_managed, "Uses Agent?", :class => "control-label col-sm-5"
        .col-sm-7
          %p.form-control-static.text-muted
            - if @node.id.blank?
              No
            - else
              - if @node.is_managed?
                Yes
              - else
                No

      .form-group
        = f.label :uuid, "UUID", :class => "control-label col-sm-5"
        .col-sm-7
          %p.form-control-static.text-muted
            - unless @node.uuid.blank?
              = @node.uuid
            - else
              Created Automatically

      .form-group
        = f.label :name, "Name", :class => "control-label col-sm-5"
        .col-sm-7
          - if @node.can_edit_special_field?
            = f.text_field :name, :class => "form-control first"
          - else
            %p.form-control-static
              = @node.name

      .form-group
        = f.label :location, "Location", :class => "control-label col-sm-5"
        .col-sm-7
          = f.text_field :location, :class => "form-control"

      .form-group
        = f.label :role, "Role", :class => "control-label col-sm-5"
        .col-sm-7
          = f.select :role, options_for_select(["Domain Controller", "Phone", "Router", "Server", "Tablet", "Workstation"], @node.role), { :include_blank => "Choose One" }, { :class => "form-control" }

      .form-group
        = f.label :architecture, "Architecture", :class => "control-label col-sm-5"
        .col-sm-7
          - if @node.can_edit_special_field?
            = f.select :architecture, options_for_select(["x86", "x64", "MIPS", "Alpha", "PowerPC", "ARM", "Itanium"], @node.architecture), { :include_blank => "Choose One" }, { :class => "form-control" }
          - else
            %p.form-control-static
              = @node.architecture

      .form-group
        = f.label :operating_system, "Operating System", :class => "control-label col-sm-5"
        .col-sm-7
          - if @node.can_edit_special_field?
            = f.select :operating_system, options_for_select(Node.operating_systems, @node.operating_system), { :include_blank => "Choose One" }, { :class => "form-control" }
          - else
            %p.form-control-static
              = @node.operating_system

      .form-group
        = f.label :service_pack_update_level, "Service Pack or Update Level", :class => "control-label col-sm-5"
        .col-sm-7
          - if @node.can_edit_special_field?
            = f.text_field :service_pack_update_level, :class => "form-control"
          - else
            %p.form-control-static
              = @node.service_pack_update_level

      .form-group
        = f.label :model_number, "Model Number", :class => "control-label col-sm-5"
        .col-sm-7
          - if @node.can_edit_special_field?
            = f.text_field :model_number, :class => "form-control"
          - else
            %p.form-control-static
              = @node.model_number

      .form-group
        = f.label :serial_number, "Serial Number", :class => "control-label col-sm-5"
        .col-sm-7
          - if @node.can_edit_special_field?
            = f.text_field :serial_number, :class => "form-control"
          - else
            %p.form-control-static
              = @node.serial_number

      .form-group
        .col-sm-offset-5.col-sm-7
          = f.submit "Save Changes", :class => "btn btn-primary"
          = f.submit "Clear", :name => "reset", :type => "reset", :class => "btn btn-default"
          = link_to "Cancel", :back, :class => "btn btn-default"

app/views/nodes/dashboard.html.haml
- content_for :title, "Dashboard"

%ol.breadcrumb
  %li.active
    Dashboard

.row
  .col-md-5.col-md-offset-1
    %h1 Welcome to Liberatio
    %h5.text-muted
      for #{current_user.organization.name},
      joined #{current_user.organization.created_at.in_time_zone.to_date.to_human}

    .row{ :style => "padding-top: 30px;" }
      .col-md-7
        %ul.list-unstyled.list-padded
          %li
            = link_to "Add Unmanaged Device", new_node_path, :class => "btn btn-primary btn-block"
          %li
            = link_to "Getting Started", browse_getting_started_path, :class => "btn btn-primary btn-block"
          %li
            = link_to "Frequently Asked Questions", browse_faq_path, :class => "btn btn-default btn-block"
          %li
            = link_to "Get Help with Liberatio", browse_contacts_path, :class => "btn btn-default btn-block"
  .col-md-5

    %h4 Quick Statistics
    %table{ :class => "table table-bordered table-condensed" }
      %tr{ :style => "background-color: #f9f9f9;" }
        %td.col-md-2.text-center
          %strong #{current_user.organization.nodes.count}
        %td{ colspan: 2 } Total Devices
      %tr
        %td.col-md-2
        %td.col-md-2.text-center
          %strong #{current_user.organization.nodes.where(is_managed: true).count}
        %td Managed
      %tr
        %td.col-md-2
        %td.col-md-2.text-center
          %strong #{current_user.organization.nodes.where(is_managed: false).count}
        %td Unmanaged
      %tr
        %td.col-md-2
        %td.col-md-2.text-center
          %strong #{current_user.organization.updates.where(is_installed: false).count(:node_id)}
        %td Needing Updates
      %tr{ :style => "background-color: #f9f9f9;" }
        %td.col-md-2.text-center
          %strong #{current_user.organization.instances.count(:application_id)}
        %td{ colspan: 2 } Total Applications

app/views/nodes/edit.html.haml
- content_for :title, "Editing #{@node.name}"

%ol.breadcrumb
  %li
    = link_to "Devices", nodes_path
  %li
    = link_to @node.name, node_path(@node)
  %li.active
    Editing

= render 'form'

app/views/nodes/index.html.haml
- content_for :title, "Devices"

%ol.breadcrumb
  %li.active
    Devices

.row
  .col-md-8
    %table.table.table-bordered.table-striped.table-condensed
      %thead
        %tr
          %th.col-md-2 Role
          %th.col-md-3 Name
          %th Operating System
          %th Location
          %th

      %tbody
        - if @nodes.any?
          - @nodes.each do |node|
            - if !(node.is_managed? && node.inventoried_at.blank?)
              %tr
                %td
                  = image_tag("#{node.role}.png".downcase, :alt => node.role, :style => "width: 16px;")
                  = node.role
                %td
                  = link_to node.name, node_path(node)
                %td #{node.operating_system}
                %td #{node.location}
                %td #{link_to 'Details', node_path(node)}
        - else
          %tr
            %td{ colspan: 6 }
              Oh no! You haven't added any devices yet -
              = link_to "Add One Now", new_node_path
              / TODO add image of oh no or something. have it link to a modal that displays instructions

  .col-md-4

    .alert.alert-warning.alert-dismissable
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      %p <strong>Liberatio Agent only supports Windows at this time</strong>
      %p
        #{link_to 'Get our newsletter', settings_user_path(current_user)} and be the first to know when we add other systems,
        and keep an eye on our #{link_to "Roadmap", browse_features_path}.
        <strong>But keep in mind</strong>, you can add devices of any type, manually without using the Agent.

    = link_to "Add Unmanaged Device", new_node_path, :class => "btn btn-primary btn-block"

    %br/

    .alert.alert-info.registration-code
      Registration Code
      %strong
        = current_user.organization.registration_code
      = link_to "javascript:void(0)", :class => "command-regenerate_registration_code" do
        %span.glyphicon.glyphicon-refresh
      %br/
      %small #{link_to 'Install the Agent', browse_download_path} on your devices and register with this code.

app/views/nodes/maintenance.html.haml
- content_for :title, "Maintenance"

%ol.breadcrumb
  %li.active
    Maintenance

.row
  .col-md-4
    .box
      = link_to "#" do
        - if @devices_needing_updates.size == 0
          %h2 Zero
        - else
          %h2 #{@devices_needing_updates.size}
        %h4 Needing Updates
    .box.box-coming-soon
      = link_to "#" do
        %h2 Coming Soon
        %h4 Without Antivirus
    .box.box-coming-soon
      = link_to "#" do
        %h2 Coming Soon
        %h4 Without Firewall


  .col-md-offset-1.col-md-7

    %h4 Devices Needing Updates
    %table.table.table-bordered.table-striped.table-condensed
      %tr
        %th.col-md-4 Name
        %th Updates
      - if @devices_needing_updates.size == 0
        %tr
          %td{ colspan: 2 } Yay! You're devices are up-to-date!
      - else
        - @devices_needing_updates.each do |node|
          %tr
            %td
              = link_to node.name, node_path(node)
            %td #{node.updates.where(is_installed: false).count}

app/views/nodes/new.html.haml
- content_for :title, "New Device"

%ol.breadcrumb
  %li
    = link_to "Devices", nodes_path
  %li.active
    New Node

= render 'form'

app/views/nodes/protection.html.haml
%ol.breadcrumb
  %li.active
    Protection

.row
  .col-md-4
    .box
      = link_to "#" do
        - if @devices_needing_updates.size == 0
          %h2 Zero
        - else
          %h2 #{@devices_needing_updates.size}
        %h4 Needing Updates
    .box
      = link_to "#" do
        - if @devices_with_issues.size == 0
          %h2 Zero
        - else
          %h2 #{@devices_with_issues.size}
        %h4 With Other Issues
    .box.box-coming-soon
      = link_to "#" do
        %h2 Coming Soon
        %h4 Without Antivirus
    .box.box-coming-soon
      = link_to "#" do
        %h2 Coming Soon
        %h4 Without Firewall


  .col-md-offset-1.col-md-7

    %h4 Devices Needing Updates
    %table.table.table-bordered.table-striped.table-condensed
      %tr
        %th.col-md-4 Name
        %th Updates
      - if @devices_needing_updates.size == 0
        %tr
          %td{ colspan: 2 } Yay! You're devices are up-to-date!
      - else
        - @devices_needing_updates.each do |node|
          %tr
            %td
              = link_to node.name, node_path(node)
            %td #{node.updates.where(is_installed: false).count}

    %br/

    %h4 Devices With Other Issues
    %table.table.table-bordered.table-striped.table-condensed
      %tr
        %th.col-md-4 Name
        %th Issue
      - if @devices_with_issues.size == 0
        %tr
          %td{ colspan: 2 } Yay! You're devices don't have any issues!
      - else
        - @devices_with_issues.each do |issue|
          %tr
            %td
              = link_to issue.node.name, node_path(issue.node)
            %td #{issue.title}