config/routes.rb
Liberatio::Application.routes.draw do

  resources :subscriptions do
    get 'welcome', :on => :collection, :as => "welcome"
  end

  get "au/latest" => "automatic_updates#latest"

  resources :issues

  resources :responses
  resources :tickets

  post "pusher/auth" => "pusher#auth"
  post "pusher/webhook" => "pusher#webhook"

  get "browse/home" => "browse#home"
  get "browse/about" => "browse#about", :as => "browse_about"
  get "browse/contacts" => "browse#contacts", :as => "browse_contacts"
  get "browse/privacy" => "browse#privacy", :as => "browse_privacy"
  get "browse/pricing" => "browse#pricing", :as => "browse_pricing"
  get "browse/features" => "browse#features", :as => "browse_features"
  get "browse/buy" => "browse#buy", :as => "browse_buy"
  get "browse/download" => "browse#download", :as => "browse_download"
  get "browse/getting_started" => "browse#getting_started", :as => "browse_getting_started"
  get "browse/faq" => "browse#faq", :as => "browse_faq"
  get "browse/documentation" => "browse#documentation", :as => "browse_documentation"
  get "browse/configuring_agent" => "browse#configuring_agent", :as => "browse_configuring_agent"

  resources :inventories, :only => :create
  resources :users do
    get 'settings', :on => :member, :as => 'settings'
  end
  resources :instances
  resources :applications
  resources :organizations do
    resources :hosted_files
    resources :notes
    get 'regenerate_registration_code', on: :collection
  end
  resources :nodes do
    resources :commands
    resources :hosted_files
    resources :notes
    get 'registered', :on => :collection
    post 'register', :on => :collection
    get 'maintenance', :on => :collection, :as => "maintenance"
    get 'dashboard', :on => :collection, :as => "dashboard"
  end

  resources :sessions
  get "sessions/new" => "sessions#new", :as => "login"
  delete "sessions/destroy" => "sessions#destroy", :as => "logout"
  get "sessions/forgot_password" => "sessions#forgot_password", :as => "forgot_password"

  root 'browse#home'
end

app/models/subscription.rb
# -----------------------------------------------------------------------------
# This file is a part of Liberatio, a systems management Web application.
# The text in this file is subject to the terms defined in the LICENSE file.
#
# Copyright 2014, Joshua Shane Martin
# All Rights Reserved
# -----------------------------------------------------------------------------

class Subscription < ActiveRecord::Base
  belongs_to :organization

  attr_accessor :stripe_card_token

  scope :active, -> { where(status: 'active') }
  scope :inactive, -> { where(status: 'inactive') }

  validates :organization, presence: true

  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: self.organization_id,  plan: "Bang", card: self.stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
  end
end

app/controllers/subscriptions_controller.rb
# -----------------------------------------------------------------------------
# This file is a part of Liberatio, a systems management Web application.
# The text in this file is subject to the terms defined in the LICENSE file.
#
# Copyright 2014, Joshua Shane Martin
# All Rights Reserved
# -----------------------------------------------------------------------------

class SubscriptionsController < ApplicationController
  skip_before_filter :authenticate_user!, only: :new
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @highlight = "pricing"
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.organization = current_user.organization

    respond_to do |format|
      if @subscription.save_with_payment
        format.html { redirect_to welcome_subscriptions_path }
      else
        flash[:alert] = @subscription.errors.full_messages
        format.html { render action: 'new' }
      end
    end
  rescue => e
    render action: 'new'
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:stripe_card_token)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.organization_id %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.haml
- content_for :title, "Signing Up"

.row{ :style => "margin-top: 60px; margin-bottom: 40px;" }

  .col-md-offset-2.col-md-4

    .row

      %h4.signing-up.text-grayed Great, you're signing up for
      = image_tag("banner-logo.png", :alt => "Liberatio Logo", :class => "buy-logo")
      
      #plan-details.text-grayed
        %h5 What you're getting for <strong>#{number_to_currency(59)}</strong>/month

        .row
          .col-md-5
            %ul.list-unstyled
              %li Unlimited Devices
              %li Hardware Inventory
              %li Software Inventory
          .col-md-7
            %ul.list-unstyled
              %li Real-Time Windows Agent
              %li Execute Commands Remotely
              %li Determine Needed Updates
    
  .col-md-offset-1.col-md-4

    .row

    - if !current_user
      %h5 To continue, just sign in or register:
      .row
        .col-md-4
          = link_to "Sign In", new_session_path(signup: true), :class => "btn btn-primary btn-lg btn-block"
        .col-md-4
          = link_to "Register", new_user_path(signup: true), :class => "btn btn-primary btn-lg btn-block"
    - else
      = form_for @subscription, :html => { :class => "form", :role => "form" } do |f|
        = f.hidden_field :stripe_card_token

        .form-group
          = label_tag :card_number, "Credit or Debit Card Number"
          = text_field_tag :card_number, nil, name: nil, :class => "form-control first"

        .form-group
          = label_tag :card_code, "Security Code on Card (CVV)"
          = text_field_tag :card_code, nil, name: nil, :class => "form-control"

        .form-group
          = label_tag :card_month, "Card Expiration"
          .row
            .col-md-6
              = select_month nil, { add_month_numbers_true: true }, { name: nil, id: "card_month", :class => "form-control" }
            .col-md-6
              = select_year nil, { start_year: Date.today.year, end_year: Date.today.year + 15 }, { name: nil, id: "card_year", :class => "form-control" }

        #stripe_error
          %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
        
        .form-group{ :style => "padding-top: 20px;" }
          = f.submit "Start Subscribtion &#x279e;".html_safe, :class => "btn btn-primary"

      %p.text-small.text-muted{ :style => "padding-top: 30px;" }
        %strong We Accept
        %br/
        = image_tag("cards/visa-32.png", :alt => "Visa")
        = image_tag("cards/mastercard-32.png", :alt => "Mastercard")
        = image_tag("cards/amex-32.png", :alt => "American Express")
        %br/
        and Discover, Diners Club, JCB

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @subscription.organization_id %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/welcome.html.haml
- content_for :title, "Signed Up"

.row{ :style => "margin-top: 60px; margin-bottom: 40px;" }

  .col-md-offset-3.col-md-8

    .row

      %h2 Congratulations, You've Got Liberatio!
      / %p.text-grayed You're signed up now, and you'll be billed <strong>#{number_to_currency(59)}</strong> monthly
      %p.text-grayed You're signed up now, and you're a part of the <strong>free public beta</strong>
      
      %br/

      %p
        = link_to dashboard_nodes_path, :class => "btn btn-primary btn-lg" do
          Continue to Liberatio Dashboard
          &#x279e;