config/routes.rb
Liberatio::Application.routes.draw do

  resources :subscriptions do
    get 'welcome', :on => :collection, :as => "welcome"
  end

  get "au/latest" => "automatic_updates#latest"

  resources :issues

  resources :responses
  resources :tickets

  post "pusher/auth" => "pusher#auth"
  post "pusher/webhook" => "pusher#webhook"

  get "browse/home" => "browse#home"
  get "browse/about" => "browse#about", :as => "browse_about"
  get "browse/contacts" => "browse#contacts", :as => "browse_contacts"
  get "browse/privacy" => "browse#privacy", :as => "browse_privacy"
  get "browse/pricing" => "browse#pricing", :as => "browse_pricing"
  get "browse/features" => "browse#features", :as => "browse_features"
  get "browse/buy" => "browse#buy", :as => "browse_buy"
  get "browse/download" => "browse#download", :as => "browse_download"
  get "browse/getting_started" => "browse#getting_started", :as => "browse_getting_started"
  get "browse/faq" => "browse#faq", :as => "browse_faq"
  get "browse/documentation" => "browse#documentation", :as => "browse_documentation"
  get "browse/configuring_agent" => "browse#configuring_agent", :as => "browse_configuring_agent"

  resources :inventories, :only => :create
  resources :users do
    get 'settings', :on => :member, :as => 'settings'
  end
  resources :instances
  resources :applications
  resources :organizations do
    resources :hosted_files
    resources :notes
    get 'regenerate_registration_code', on: :collection
  end
  resources :nodes do
    resources :commands
    resources :hosted_files
    resources :notes
    get 'registered', :on => :collection
    post 'register', :on => :collection
    get 'maintenance', :on => :collection, :as => "maintenance"
    get 'dashboard', :on => :collection, :as => "dashboard"
  end

  resources :sessions
  get "sessions/new" => "sessions#new", :as => "login"
  delete "sessions/destroy" => "sessions#destroy", :as => "logout"
  get "sessions/forgot_password" => "sessions#forgot_password", :as => "forgot_password"

  root 'browse#home'
end

app/controllers/browse_controller.rb
# -----------------------------------------------------------------------------
# This file is a part of Liberatio, a systems management Web application.
# The text in this file is subject to the terms defined in the LICENSE file.
#
# Copyright 2014, Joshua Shane Martin
# All Rights Reserved
# -----------------------------------------------------------------------------

class BrowseController < ApplicationController
  skip_before_filter :authenticate_user!

  # GET /browse/home
  def home
  end

  # GET /browse/configuring_agent
  def configuring_agent
    @highlight = "docs"
  end

  # GET /browse/documentation
  def documentation
    @highlight = "docs"
  end

  # GET /browse/faq
  def faq
    @highlight = "docs"
  end

  # GET /browse/getting_started
  def getting_started
    @highlight = "docs"
  end

  # GET /browse/download
  def download
    @highlight = "download"
  end

  # GET /browse/pricing
  def pricing
    @highlight = "pricing"
  end

  # GET /browse/sign_up
  def buy
    @highlight = "pricing"
    @subscription = Subscription.new

    # Set session variable
    if params.has_key?(:plan)
      plan = { :name => params[:plan]  }
      case params[:plan]
      when "Brook"
        plan[:price_cents] = 19*100
        plan[:devices] = 5
        plan[:assisted] = 1
      when "Stream"
        plan[:price_cents] = 89*100
        plan[:devices] = 25
        plan[:assisted] = 5
      when "Creek"
        plan[:price_cents] = 299*100
        plan[:devices] = 100
        plan[:assisted] = 20
      when "River"
        plan[:price_cents] = 599*100
        plan[:devices] = 500
        plan[:assisted] = 50
      end
      session[:plan] = plan
    end
  end

  # GET /browse/features
  def features
    @highlight = "features"
  end

  # GET /browse/roadmap
  def roadmap
    @highlight = "features"
  end
end

app/views/browse/about.html.haml
- content_for :title, "About"

= render partial: "layouts/onboarding_banner"

.row.row-padded

  .col-md-6
    %h2 About Liberatio
    %br/
    %p.expanded Liberatio is a cloud-based systems management tool designed to give you greater control and insight over your IT devices and infrastructure. Agents are a key component that, when deployed on your devices, enable real-time, two-way communication and management securely over the Web.
    %p.expanded Liberatio is a personal project of Joshua Shane Martin, Co-founder and CTO of Nfoshare.com, who was previously the IT Manager of a document management firm.
    %p.expanded
      %strong Contact him at josmar52789 [at] gmail [dot] com

app/views/browse/buy.html.haml
- content_for :title, "Signing Up"

.row{ :style => "margin-top: 60px; margin-bottom: 40px;" }

  .col-md-offset-2.col-md-4

    .row

      %h4.signing-up.text-grayed Great, you're signing up for
      = image_tag("banner-logo.png", :alt => "Liberatio Logo", :class => "buy-logo")
      
      #plan-details.text-grayed
        %h5 What you're getting for <strong>#{number_to_currency(59)}</strong>/month

        .row
          .col-md-5
            %ul.list-unstyled
              %li Unlimited Devices
              %li Hardware Inventory
              %li Software Inventory
          .col-md-7
            %ul.list-unstyled
              %li Real-Time Windows Agent
              %li Execute Commands Remotely
              %li Determine Needed Updates
    
  .col-md-offset-1.col-md-4

    .row

    - if !current_user
      %h5 To continue, just sign in or register:
      .row
        .col-md-4
          = link_to "Sign In", new_session_path, :class => "btn btn-primary btn-lg btn-block"
        .col-md-4
          = link_to "Register", new_user_path, :class => "btn btn-primary btn-lg btn-block"
    - else
      = form_for @subscription, :html => { :class => "form", :role => "form" } do |f|
        = f.hidden_field :stripe_card_token

        .form-group
          = label_tag :card_number, "Credit or Debit Card Number"
          = text_field_tag :card_number, nil, name: nil, :class => "form-control first"

        .form-group
          = label_tag :card_code, "Security Code on Card (CVV)"
          = text_field_tag :card_code, nil, name: nil, :class => "form-control"

        .form-group
          = label_tag :card_month, "Card Expiration"
          .row
            .col-md-6
              = select_month nil, { add_month_numbers_true: true }, { name: nil, id: "card_month", :class => "form-control" }
            .col-md-6
              = select_year nil, { start_year: Date.today.year, end_year: Date.today.year + 15 }, { name: nil, id: "card_year", :class => "form-control" }

        #stripe_error
          %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.

        = f.submit "Subscribe", :class => "btn btn-primary"

      %p.text-small.text-muted{ :style => "padding-top: 30px;" }
        %strong We Accept
        %br/
        = image_tag("cards/visa-32.png", :alt => "Visa")
        = image_tag("cards/mastercard-32.png", :alt => "Mastercard")
        = image_tag("cards/amex-32.png", :alt => "American Express")
        %br/
        and Discover, Diners Club, JCB

app/views/browse/configuring_agent.html.haml
- content_for :title, "Configuring Liberatio Agent"

%ol.breadcrumb
  %li #{link_to "Documentation", browse_documentation_path}
  %li.active
    Configuring Liberatio Agent

.row
  .col-md-9
    %h3
      Configuring Liberatio Agent
      %br/
      %small Authored by Joshua Shane Martin | April 15, 2014

    %p.padded Liberatio Agent can be configured manually via the configuration file, or via the GUI; Liberatio Agent is only supported on Windows at this time.

    %br/

    .row

      .col-md-10.col-md-offset-1

        %h4 Windows (Graphical User Interface)
        %p.padded
          Launch the Liberatio Agent Tray Icon located at:
          %br/
          %pre Start > All Programs > Liberatio > <strong>Liberatio Agent</strong>

        %br/

        %h4 Windows (Configuration File)
        %p.padded Edit the configuration file using Notepad, text editor, or an XML Editor located at:
        %p.padded
          %strong Windows 32-bit Versions
          %br/
          %pre C:\Program Files\Liberatio Agent\LiberatioService.xml.config
        %p.padded
          %strong Windows 64-bit Versions
          %br/
          %pre C:\Program Files (x86)\Liberatio Agent\LiberatioService.xml.config

app/views/browse/contacts.html.haml
- content_for :title, "Contacts"

= render partial: "layouts/onboarding_banner"

.row.row-padded

  .col-md-4
    %h2 Contacts
    %br/
    %p.expanded Give us a shout at the appropriate Email address and we'll get back to you within 24 business hours.

  .col-md-6.col-md-offset-1
    %h3 #{mail_to "sales@getliberatio.com"}
    %h5.text-muted Sales Inquiries
    %h3 #{mail_to "support@getliberatio.com"}
    %h5.text-muted Technical, Billing Questions
    %h3 #{mail_to "admin@getliberatio.com"}
    %h5.text-muted Questions, Comments

app/views/browse/documentation.html.haml
- content_for :title, "Documentation"

= render partial: "layouts/onboarding_banner"

%h2 Documentation

%br/
%br/

.row
  .col-md-5.col-md-offset-1
    %h4 Articles
    %ul.list-padded
      %li #{link_to "Getting Started", browse_getting_started_path}
      %li #{link_to "Frequently Asked Questions", browse_faq_path}
      %li #{link_to "Configuring Liberatio Agent", browse_configuring_agent_path}

  .col-md-6
    %h4 Need Help? Email us at
    %h3{ :style => "margin-top: 0; font-weight: bold;" }
      = mail_to "support@getliberatio.com"

%br/

app/views/browse/download.html.haml
- content_for :title, "Download Agent"

= render partial: "layouts/onboarding_banner"

%h2 Download the Agent

.row{ :style => "padding-top: 20px;" }

  .col-md-5
    %h4.text-liberatio-primary.cursive What does the Agent do?
    %p Install this agent on your machines (servers, workstations, laptops) to have an Asset Inventory sent to Liberatio automatically. The Agent also enables features like shutting down and restarting remotely, as well as executing commands remotely.

    %p Liberatio Agent only supports Windows at this time, but watch our #{link_to "Roadmap", browse_features_path}. <strong>And keep in mind</strong>, you can add devices of any type, manually without using the Agent.

  .col-md-6
    .alert.alert-warning
      %p <strong>Liberatio Agent only supports Windows at this time</strong>

    %ul.nav.nav-tabs
      %li.active
        = link_to "Windows", "#windows", "data-toggle" => "tab"
      %li
        = link_to "OS X", "#osx", "data-toggle" => "tab"
      %li
        = link_to "Linux", "#linux", "data-toggle" => "tab"

    .tab-content

      #windows.tab-pane.active
        %p.text-muted
          Version 1.0.0.0, Released March 13, 2014
        %p
          = link_to "Download Now", "#", :class => "btn btn-primary"
          = link_to "View Source", "https://github.com/joshuasmartin/liberatio-agent-windows/", :class => "btn btn-default"

        %p.text-muted
          %small Supports Windows Vista, 7, 8, 2003, 2008, 2008 R2, 2012. Requires .NET 4 Client Profile.

      #osx.tab-pane
        %p
          Coming Soon,
          - if current_user
            #{link_to 'Get Notified', settings_user_path(current_user)} when we add this platform
          - else
            Sign Up for the Newsletter in Settings to get notified when we add this platform

      #linux.tab-pane
        %p
          Coming Soon,
          - if current_user
            #{link_to 'Get Notified', settings_user_path(current_user)} when we add this platform
          - else
            Sign Up for the Newsletter in Settings to get notified when we add this platform

app/views/browse/faq.html.haml
- content_for :title, "Frequently Asked Questions"

%ol.breadcrumb
  %li #{link_to "Documentation", browse_documentation_path}
  %li.active
    Frequently Asked Questions

.row
  .col-md-9
    %h3
      Frequently Asked Questions
      %br/
      %small Authored by Joshua Shane Martin | April 9, 2014

.row
  .col-md-5

    %h4 What does Liberatio do?
    %p.padded Liberatio is a cloud-based systems management tool designed to give you greater control and insight over your IT devices and infrastructure. Agents are a key component that, when deployed on your devices, enable real-time, two-way communication and management securely over the Web.
    %p.padded More specifically, Liberatio consists of two components - the Liberatio Website, which provides an API and management interface, and software agents that are deployed onto devices to enable real-time management and inventory.

    %br/
    %br/

    %h4 What is a "Registration Code"?
    %p.padded The <strong>registration code</strong> is a string of characters that serve as a way to <em>initially associate</em> your Agents with your Liberatio account. After installing Liberatio Agent on a computer, you must enter the registration code in the Agent's configuration and restart the Agent - the Agent will perform the necessary steps to securely associate itself with your account upon restart.
    %p.padded The following steps will be taken on restart:
    %ol.list-padded
      %li Agent detects a registration code in configuration.
      %li Agent connects to Liberatio Website.
      %li Agent is registered and associated with your account.
      %li Website responds with a <strong>Communication Token</strong>.
      %li The Communication Token is saved to the configuration.
    %p.padded Every subsequent contact with the server includes the Communication Token to authenticate the request (the Communication Token is stored on the server to ensure that the Communication Token coming from the Agent matches the one on the server).

  .col-md-5.col-md-offset-1

    %h4 What is a "Communication Token"?
    %p.padded The <strong>Communication Token</strong> is a security token that is passed back and forth between the server and agent to authenticate that requests from the agent are valid.
    %p.padded A communication token is generated automatically by the Liberatio Website when the agent is registered, when the communication token is saved to the configuration for future communications. Every transmission from the agent will contain the communication token, which will be compared to the token on the server.
    %p.padded Communication Tokens are unique for each device.

app/views/browse/features.html.haml
- content_for :title, "Features"

= render partial: "layouts/onboarding_banner"

%h2 Simple, Powerful Features

%br/

.row

  / details
  .col-md-8

    %ul.nav.nav-pills
      %li.active
        = link_to "Inventory", "#inventory", "data-toggle" => "pill"
      %li
        = link_to "Remote Commands", "#remote-commands", "data-toggle" => "pill"
      %li
        = link_to "System Cleanup", "#cleanup", "data-toggle" => "pill"
      %li
        = link_to "Agent", "#agent", "data-toggle" => "pill"
      %li
        = link_to "Open Source", "#foss", "data-toggle" => "pill"
      %li
        = link_to "Roadmap", "#roadmap", "data-toggle" => "pill"

    .tab-content

      #inventory.tab-pane.active
        .row
          .col-md-6
            %h4.text-liberatio-primary.cursive.feature-title What gets inventoried?
            %p The Agent inventories both hardware and software:
            %ul.list-liberatio-padded
              %li Model and Serial Number
              %li Storage Devices
              %li Processors and Memory
              %li Network Interfaces
              %li Operating System Name and Version
              %li Software Applications Installed
              %li Windows Updates Installed
              %li Windows Updates Needed
          .col-md-offset-1.col-md-3
            = image_tag("features/inventory.png", :alt => "Inventory", :class => "text-center btn-block")

      #remote-commands.tab-pane
        .row
          .col-md-6
            %h4.text-liberatio-primary.cursive.feature-title What are "Remote Commands" ?
            %p Liberatio Agent allows you to run executables (with parameters) and typical "Command Prompt" commands on a remote device via the Liberatio Dashboard.
            %p This powerful feature enables you to do things like delete files, run batch files, or execute binaries from a remote location over secure, encrypted channels in the context of a privileged account (i.e. Administrator account).
            %p The result of the Remote Command is available to you immediately upon execution due to our unique, direct, two-way communication with the remote device (using standard, open, secure protocols).
          .col-md-offset-1.col-md-3
            = image_tag("features/commands.png", :alt => "Commands", :class => "text-center btn-block")

        %br/

        .row
          .col-md-6
            %h4.text-liberatio-primary.cursive.feature-title What kind of commands can I execute?
            %p Examples would include:
            %p
              %pre rd /s /q "C:\Folder"
            %p
              %pre sfc /scanboot
            %p
              %pre C:\mybat.bat
          .col-md-6
            %h4.text-liberatio-primary.cursive.feature-title Is it secure?
            %p Absolutely.
            %p The commands are sent over secure, encrypted WebSockets; and the user account on the remote device is a privileged account whose password resets automatically every time the Agent is started. This account is kept disabled until it is needed, and the password is generated and stored (encrypted) in a file that only the Agent can read.
            %p Only you can execute Remote Commands, and a record of all Remote Commands is logged.


      #cleanup.tab-pane
        .row
          .col-md-6
            %h4.text-liberatio-primary.cursive.feature-title What is System Cleanup ?
            %p System Cleanup is performed automatically by the Liberatio Agent on a regular basis in order to improve the performance of your system and reclaim storage space.
            %p The cleanup consists of:
            %ul.list-liberatio-padded
              %li Clearing Windows Prefetch
              %li Clear the Windows Update Download Cache
              %li Flush the DNS Cache
              %li Delete Archived System Error Reporting Logs
          .col-md-offset-1.col-md-3
            = image_tag("features/cleanup.png", :alt => "Cleanup", :class => "text-center btn-block")

      #agent.tab-pane
        .row
          .col-md-6
            %h4.text-liberatio-primary.cursive.feature-title What is the Agent?
            %p The Agent is a software application that runs on all of your devices. It's responsible for collecting an inventory of your hardware and software, enabling commands to be executed remotely from the Website, and performing a cleanup of your system at predefined intervals.
            %p Real-time communication between the Website and Agent is achieved using standard HTML5 WebSockets; communication can be made through firewalls, proxies, and other traditional network obstacles.
            %p
              %strong At this time, a Liberatio Agent is only available for Windows systems.
              Other systems and platforms will become available as soon as possible; keep an eye on our Roadmap, and sign up for the Newsletter to be notified of when we add new ones.
          .col-md-offset-1.col-md-3
            = image_tag("features/agent.png", :alt => "Agent", :class => "text-center btn-block")

      #foss.tab-pane
        .row
          .col-md-6
            %h4.text-liberatio-primary.cursive.feature-title Liberatio Agents are Open
            %p The Agent(s) for every platform will always be Open Source to ensure that you can see exactly what information we collect, how we collect it, and what we do it with.
            %p The source code for the Liberatio Agent for Windows is licensed under the GPLv3 and is #{link_to 'available on GitHub', 'https://github.com/joshuasmartin/liberatio-agent-windows'}.
          .col-md-offset-1.col-md-3
            = image_tag("features/code.png", :alt => "Source Code", :class => "text-center btn-block")

      #roadmap.tab-pane
        .row
          .col-md-6
            %h4.text-liberatio-primary.cursive.feature-title Coming Soon
            %ul.list-liberatio-padded
              %li Alerts for System Issues
              %li Antivirus and Firewall Discovery
              %li Software Deployment
              %li Linux Agent
              %li OS X Agent
              %li BSD Agent
              %li iOS Agent
              %li Android Agent
          .col-md-offset-1.col-md-3
            = image_tag("features/roadmap.png", :alt => "Roadmap", :class => "text-center btn-block")

  / at a glance
  .col-md-4
    %h4 Features at a Glance

    %table{ :class => "table table-bordered" }
      %tr
        %td.text-center &#x2713;
        %td Automatic Hardware Inventory
      %tr
        %td.text-center &#x2713;
        %td Automatic Software Inventory
      %tr
        %td.text-center &#x2713;
        %td Discover Needed Updates
      %tr
        %td.text-center &#x2713;
        %td Execute Commands Remotely
      %tr
        %td.text-center &#x2713;
        %td Automatic System Cleanup
      %tr
        %td.text-center &#x2713;
        %td Real-Time Windows Agent

%hr/

%p
  Have a question about a feature or want to suggest a new feature?
  = link_to "Contact Us", browse_contacts_path, :class => "btn btn-primary btn-sm"

app/views/browse/getting_started.html.haml
- content_for :title, "Getting Started"

%ol.breadcrumb
  %li #{link_to "Documentation", browse_documentation_path}
  %li.active
    Getting Started

.row
  .col-md-9
    %h3
      Getting Started with Liberatio
      %br/
      %small Authored by Joshua Shane Martin | April 9, 2014

    %p.padded After you've signed up for Liberatio on the Website, you can begin by either adding devices of any type or system manually (called Unmanaged Devices), or by installing the Agent (called Managed Devices) on devices to have them inventoried, and to enable additional functionality such as Remote Commands, etc.

    %br/

    .row

      .col-md-10.col-md-offset-1

        %h4 Adding Unmanaged Devices
        %p.padded Unmanaged Devices are devices that do not have an agent installed, which means that you add them manually in the Liberatio Dashboard in order to record and store information about them.
        %ol.list-padded
          %li Go to the <strong>Liberatio Dashboard</strong>.
          %li Click the <strong>Devices</strong> tab.
          %li Click the "Add Unmanaged Device" button.

        %br/

        %h4 Adding Managed Devices
        %p.padded Managed Devices are devices that have the Liberatio Agent installed and running; they are automatically added to the Liberatio Dashboard during the device registration process, and have advanced functionality like Remote Commands, automatic hardware and software inventory, System Cleanup, etc.
        %ol.list-padded
          %li #{link_to "Download", browse_download_path} the Liberatio Agent for the correct platform.
          %li Install the agent.
          %li
            Add your <strong>registration code</strong> to the agent's configuration.
            %p
              .alert.alert-info.alert-small
                #{link_to "See the documentation", browse_configuring_agent_path} for how to edit the configuration on each platform.
          %li Restart the agent (or the device).
          %li The device will register in the Liberatio Dashboard.

app/views/browse/home.html.haml
- content_for :title, "Asset Inventory, Remote Management"

.row{ :style => "padding-top: 40px; padding-bottom: 30px;" }
  .col-md-5.col-md-offset-1.text-center
    = image_tag("banner-logo.png", :alt => "")
  .col-md-5
    %h2.cursive{ :style => "line-height: 40px;" }
      Simple, Powerful, Cloud-based Systems Management
    %h3{ :style => "line-height: 40px; padding-bottom: 10px; color: Green;" } Free During the Public Beta
    - if beta?
      = link_to new_user_path, :class => "btn btn-primary btn-lg" do
        Get Liberatio Beta Now &#x279e;
    - else
      = link_to new_subscription_path, :class => "btn btn-primary btn-lg" do
        Get Liberatio Now &#x279e;
    &nbsp;
    &nbsp;
    = link_to browse_features_path, :class => "btn btn-default btn-lg" do
      Learn More

%hr/

.row.product-details
  .col-md-4
    = image_tag("what.png", :alt => "What is Liberatio?", :class => "pull-left", :style => "padding-right: 15px;")
    %h4.text-liberatio-primary.cursive What is Liberatio?
    %h5 Liberatio is a cloud-based systems management tool designed to give you greater control and insight over your IT devices and infrastructure. Agents are a key component that, when deployed on your devices, enable real-time, two-way communication and management securely over the Web.

  .col-md-4
    = image_tag("who.png", :alt => "Who is Liberatio for?", :class => "pull-left", :style => "padding-right: 15px;")
    %h4.text-liberatio-primary.cursive Who is Liberatio for?
    %h5 IT Managers, IT guys, and System Administrators who need to get a handle on their IT infrastructure. Liberatio works well in small to mid-size environments, and can be used to manage from just one to 1000+ devices. Liberatio works securely over the Web, and requires no firewall or network modifications.

  .col-md-4
    = image_tag("do.png", :alt => "What can Liberatio do?", :class => "pull-left", :style => "padding-right: 15px;")
    %h4.text-liberatio-primary.cursive What can Liberatio do?
    %h5 Liberatio enables you to streamline your IT infrastructure by improving the way you manage your devices. Automatic hardware and software inventory, real-time communication, and continual monitoring will not only help you resolve issues, but also prevent them from occuring.

app/views/browse/pricing.html.haml
- content_for :title, "Pricing Information"

= render partial: "layouts/onboarding_banner"

- if beta?

  %h2 Use Liberatio for Free

  %br/

  .row

    .col-md-6

      %p.padded During the public beta, which will last for the foreseeable future, Liberatio will be available for anyone to use for free.
      %p.padded To get started, simply #{link_to "create an account", new_user_path} and you'll have access.
      %p.padded Even if we do end the public beta, and you decide not to pay for Liberatio, you will still have access to Liberatio for a time, in order to export your data.

- else

  %h2 Simple, Direct Pricing

  .row

    .col-md-8

      .row
        .col-md-6
          %h4.pricing-question.text-liberatio-primary.cursive How do I pay?
          %p.pricing-answer On a month-by-month basis. You pay each month via a debit or credit card. You can cancel at any time.

          %h4.pricing-question.text-liberatio-primary.cursive Is there a contract?
          %p.pricing-answer No, you can cancel your subscription at any time.

          %h4.pricing-question.text-liberatio-primary.cursive What platforms are supported?
          %p.pricing-answer Only Windows is supported by our Agent at this time - the Agent sends an inventory to Liberatio, and allows you to control the machine from the Liberatio Website. Any other type of device can be added manually.

        .col-md-6
          %h4.pricing-question.text-liberatio-primary.cursive What do I get?
          %p.pricing-answer
            Simple, you get the works!
            %br/
            %ul.list-unstyled.list-padded
              %li &#x2713; Unlimited Devices
              %li &#x2713; Hardware Inventory
              %li &#x2713; Software Inventory
              %li &#x2713; Discover Needed Updates
              %li &#x2713; Execute Commands Remotely
              %li &#x2713; Automatic System Cleanup
              %li &#x2713; Real-Time Windows Agent

    .col-md-4

      %h1 $59/month
      %h4{ :style => "padding-bottom: 20px;" } Single, Simple, Unified Plan

      = link_to new_subscription_path, :class => "btn btn-primary btn-lg" do
        Sign Up Now
        &#x279e;

app/views/browse/privacy.html.haml
- content_for :title, "Terms and Privacy"

= render partial: "layouts/onboarding_banner"

.row.row-padded

  .col-md-6
    %h2 Terms and Privacy
    
    %p By accessing and using this website , you accept and agree to be bound by the terms and provision of this agreement. In addition, when using this website's particular services, you shall be subject to any posted guidelines or rules applicable to such services, which may be posted and modified from time to time. All such guidelines or rules are hereby incorporated by reference into the TOS.

    %p ANY PARTICIPATION IN THIS SITE WILL CONSTITUTE ACCEPTANCE OF THIS AGREEMENT. IF YOU DO NOT AGREE TO ABIDE BY THE ABOVE, PLEASE DO NOT USE THIS SITE.

    %hr/


    %p This site and its components are offered for informational purposes only; this site shall not be responsible or liable for the accuracy, usefulness or availability of any information transmitted or made available via the site, and shall not be responsible or liable for any error or omissions in that information.



    %p This site will collect and store your credit card number and billing information using a third party service in order to provide  recurring billing.