config/routes.rb
Liberatio::Application.routes.draw do

  resources :subscriptions do
    get 'welcome', :on => :collection, :as => "welcome"
  end

  get "au/latest" => "automatic_updates#latest"

  resources :issues

  resources :responses
  resources :tickets

  post "pusher/auth" => "pusher#auth"
  post "pusher/webhook" => "pusher#webhook"

  get "browse/home" => "browse#home"
  get "browse/about" => "browse#about", :as => "browse_about"
  get "browse/contacts" => "browse#contacts", :as => "browse_contacts"
  get "browse/privacy" => "browse#privacy", :as => "browse_privacy"
  get "browse/pricing" => "browse#pricing", :as => "browse_pricing"
  get "browse/features" => "browse#features", :as => "browse_features"
  get "browse/buy" => "browse#buy", :as => "browse_buy"
  get "browse/download" => "browse#download", :as => "browse_download"
  get "browse/getting_started" => "browse#getting_started", :as => "browse_getting_started"
  get "browse/faq" => "browse#faq", :as => "browse_faq"
  get "browse/documentation" => "browse#documentation", :as => "browse_documentation"
  get "browse/configuring_agent" => "browse#configuring_agent", :as => "browse_configuring_agent"

  resources :inventories, :only => :create
  resources :users do
    get 'settings', :on => :member, :as => 'settings'
  end
  resources :instances
  resources :applications
  resources :organizations do
    resources :hosted_files
    resources :notes
    get 'regenerate_registration_code', on: :collection
  end
  resources :nodes do
    resources :commands
    resources :hosted_files
    resources :notes
    get 'registered', :on => :collection
    post 'register', :on => :collection
    get 'maintenance', :on => :collection, :as => "maintenance"
    get 'dashboard', :on => :collection, :as => "dashboard"
  end

  resources :sessions
  get "sessions/new" => "sessions#new", :as => "login"
  delete "sessions/destroy" => "sessions#destroy", :as => "logout"
  get "sessions/forgot_password" => "sessions#forgot_password", :as => "forgot_password"

  root 'browse#home'
end

app/views/layouts/_onboarding_banner.html.haml
%p.pull-right
  Ready to get started? #{link_to "Sign Up Now", new_user_path, :class => "btn btn-primary btn-sm"}

app/views/layouts/application.html.haml
!!! 5
%html{ :lang=>"en" }
  %head
    %meta{ :charset=>"utf-8" }

    %title #{yield(:title)} - Systems Management - Liberatio

    = favicon_link_tag '/favicon.ico'
    = favicon_link_tag '/favicon.png'

    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    <link href='http://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>

    = tag :meta, :name => "stripe-key", :content => Rails.configuration.stripe[:publishable_key]
    - if true
      %script{ type: "text/javascript", src: "https://js.stripe.com/v2/" }

%body

  %nav.navbar.navbar-default.navbar-fixed-top{ role: "navigation" }
    .container
      .navbar-header
        = link_to root_path, :class => "navbar-brand" do
          = image_tag("nav-logo.png", :alt => "")

      - if @navigation == "account"
        %ul.nav.navbar-nav
          %li{ :class => ("active" if @highlight == "dashboard") }
            = link_to dashboard_nodes_path do
              = image_tag("dashboard.png", :alt => "Dashboard", :style => "height: 18px;")
              Dashboard
          %li{ :class => ("active" if @highlight == "devices") }
            = link_to nodes_path do
              = image_tag("devices.png", :alt => "Devices", :style => "height: 18px;")
              Devices
          %li{ :class => ("active" if @highlight == "software") }
            = link_to instances_path do
              = image_tag("software.png", :alt => "Software", :style => "height: 18px;")
              Software
          %li{ :class => ("active" if @highlight == "maintenance") }
            = link_to maintenance_nodes_path do
              = image_tag("protection.png", :alt => "Maintenance", :style => "height: 18px;")
              Maintenance
      - else
        %ul.nav.navbar-nav
          %li{ :class => ("active" if request.fullpath == root_path) }
            = link_to "Home", root_path
          %li{ :class => ("active" if @highlight == "features") }
            = link_to browse_features_path do
              = image_tag("features.png", :alt => "Features", :style => "height: 18px;")
              Features
          %li{ :class => ("active" if @highlight == "pricing") }
            = link_to browse_pricing_path do
              = image_tag("plans.png", :alt => "Plans and Pricing", :style => "height: 18px;")
              Pricing
          %li{ :class => ("active" if @highlight == "download") }
            = link_to browse_download_path do
              = image_tag("download.png", :alt => "Download", :style => "height: 18px;")
              Download
          %li{ :class => ("active" if @highlight == "docs") }
            = link_to browse_documentation_path do
              = image_tag("docs.png", :alt => "Documentation", :style => "height: 18px;")
              Docs

      - if current_user
        %ul.nav.navbar-nav.navbar-right
          - if (current_user.organization.subscriptions.any? || beta?) && (@navigation != "account")
            %li
              = link_to dashboard_nodes_path do
                %strong Go to Liberatio Dashboard
          %li.dropdown
            = link_to "#", "data-toggle" => "dropdown", :class => "dropdown-toggle" do
              Joshua Shane Martin
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Account", settings_user_path(current_user)
              %li.divider
              %li
                = link_to "Sign Out", logout_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to login_path do
              Sign In or Register
              = image_tag("login.png", :alt => "Sign In or Register", :style => "height: 18px;")

  .container

    .row
      .col-md-12
        - unless notice.nil?
          .alert.alert-info.alert-dismissable
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            %strong Hey!
            = notice

        - unless alert.nil?
          .alert.alert-danger.alert-dismissable
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            %strong Uh oh!
            = alert

    = yield

  %footer.container
    %hr/
    .row
      .col-md-6
        %p.text-muted
          %small #{link_to "Contact", browse_contacts_path} | #{link_to "About", browse_about_path} | #{link_to "Terms and Privacy", browse_privacy_path}
      .col-md-6
        %p.text-muted.text-right
          %small &copy; 2014, Joshua Shane Martin | Icons by #{link_to "icons8", "http://icons8.com/"}

app/views/layouts/user_mailer.html.haml
.logo{ :style => "padding: 10px 0 20px 0;" }
  = link_to "https://getliberatio.com" do
    = image_tag("http://b3030c52c2e84dc54a90-d586199d0729f94ce809eb84cce1add4.r84.cf5.rackcdn.com/banner-logo.png", :alt => "Liberatio", :style => "width: 150px; height: 40px;")

.box{:style=>"border-top:solid 2px #eee;" }

  .content{:style=>"padding:15px 20px 15px 20px; max-width:500px; min-height:330px; color:#333; font-size:16px; font-family:Arial,sans-serif; font-weight:200; line-height:1.45em; letter-spacing:.01em;" }

    - if @user
      %p
        Hi, #{@user.name}:

    -# Content of an Email is rendered here.
    = yield

    %p{:style=>"margin-top:30px;" }
      \- Liberatio Team

  .footer{:style=>"margin:20px auto 10px auto; font-size:11px; color:#999; letter-spacing:.01em; text-align:center;"}
    %a{:href=>"https://getliberatio.com", :style=>"color:#999; font-family:Arial,sans-serif;font-weight:200; "} GetLiberatio.com

    = surround ' | ', ' | ' do
      %a{:href=>"https://getliberatio.com/browse/about", :style=>"color:#999; font-family:Arial,sans-serif;font-weight:200; "} About Liberatio

    %a{:href => "https://getliberatio.com/browse/privacy", :style=>"color:#999; font-family:Arial,sans-serif;font-weight:200; "}
      Privacy + Terms